"""Phase M - run the monitoring checks and write the monitoring design report.

    python scripts/monitor.py

Compares the model's training window (reference) with the most recent served
window (current): schema conformance, feature drift, prediction drift, and
realised accuracy.

Outputs
-------
    reports/MONITORING_DESIGN.md
    artifacts/metrics/monitoring.json
"""

from __future__ import annotations

import sys
from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO_ROOT / "src"))

from pricing_engine.config import load_config  # noqa: E402
from pricing_engine.features.build import training_frame  # noqa: E402
from pricing_engine.models.demand_model import NUMERIC_FEATURES, load_model  # noqa: E402
from pricing_engine.monitoring.drift import (  # noqa: E402
    feature_drift,
    performance_when_outcomes_arrive,
    prediction_distribution_check,
    schema_check,
)
from pricing_engine.utils.io import write_json  # noqa: E402

EXPECTED_SCHEMA = {
    "upc": "int",
    "store": "int",
    "week": "int",
    "move": "float",
    "effective_unit_price": "float",
    "decision_time_unit_cost": "float",
    "recorded_promotion_flag": "int",
}


def main() -> int:
    cfg = load_config()
    model = load_model(cfg.path("models_dir") / "demand_model.joblib", cfg=cfg)
    meta = model.metadata
    feats = pd.read_parquet(cfg.path("features_table"))
    usable = training_frame(feats)

    train_lo, train_hi = meta.train_weeks
    test_lo, test_hi = meta.test_weeks
    reference = usable[(usable["week"] >= train_lo) & (usable["week"] <= train_hi)]
    current = usable[(usable["week"] >= test_lo) & (usable["week"] <= test_hi)]
    print(f"reference weeks {train_lo}-{train_hi} ({len(reference):,} rows), "
          f"current weeks {test_lo}-{test_hi} ({len(current):,} rows)")

    schema = schema_check(current, EXPECTED_SCHEMA)
    drift = feature_drift(reference, current, [f for f in NUMERIC_FEATURES if f != "upc_demand_prior"])

    ref_sample = reference.sample(min(200_000, len(reference)), random_state=cfg.seed)
    cur_sample = current.sample(min(200_000, len(current)), random_state=cfg.seed)
    pred_check = prediction_distribution_check(model.predict(ref_sample), model.predict(cur_sample))

    scored = current.copy()
    scored["pred"] = model.predict(current)
    scored["period"] = scored["week_start_date"].dt.to_period("Q").astype(str)
    perf = performance_when_outcomes_arrive(scored, "move", "pred", "period")

    payload = {
        "model_version": meta.version,
        "reference_weeks": [train_lo, train_hi],
        "current_weeks": [test_lo, test_hi],
        "schema": schema,
        "feature_drift": [d.as_dict() for d in drift],
        "prediction_drift": pred_check,
        "performance_by_quarter": [p.as_dict() for p in perf],
    }
    write_json(cfg.path("metrics_dir") / "monitoring.json", payload)

    top = drift[:12]
    drift_rows = "\n".join(
        f"| `{d.feature}` | {d.psi:.4f} | {d.band} | {d.ks:.4f} | {d.reference_mean:,.3f} | {d.current_mean:,.3f} |"
        for d in top
    )
    perf_rows = "\n".join(
        f"| {p.period} | {p.n:,} | {p.metrics['mae']:.2f} | {p.metrics['rmse']:.2f} | "
        f"{p.metrics['wape']:.4f} | {p.metrics['bias']:+.2f} |"
        for p in perf
    )

    report = f"""# Monitoring design

Generated by `python scripts/monitor.py` (model `{meta.version}`).

Reference window = the model's training weeks {train_lo}-{train_hi}.
Current window = the held-out weeks {test_lo}-{test_hi}, standing in for
"what production would see after deployment".

## 1. What is monitored, and why

| check | question | alarm value |
| --- | --- | --- |
| schema | did the input contract change? | hard failure - refuse to score |
| feature drift (PSI / KS) | do inputs look like training data? | investigate |
| prediction drift | did the output distribution move? | investigate |
| realised accuracy | is the model still right once outcomes arrive? | the only real alarm |
| price-response sanity | is the demand curve still downward sloping? | blocks pricing, not forecasting |

Ordering matters: drift alone never proves failure, and a drifting feature with
stable accuracy usually means the feature was not load-bearing. Only realised
accuracy (and price-response sanity) should gate pricing decisions.

## 2. Schema check

```json
{{"passed": {str(schema['passed']).lower()}, "missing_columns": {schema['missing_columns']}, "unexpected_dtypes": {schema['unexpected_dtypes']}, "rows": {schema['rows']}}}
```

## 3. Feature drift (top 12 by PSI)

| feature | PSI | band | KS | reference mean | current mean |
| --- | --- | --- | --- | --- | --- |
{drift_rows}

**Interpretation limits.** The 0.10 / 0.25 PSI bands are industry folklore, not
statistical thresholds: PSI depends on bin count and sample size and has no
associated test. KS is reported as a *statistic* only - with hundreds of
thousands of rows, any KS test rejects equality, so p-values are useless here.
Drift on price and lagged-demand features is expected in this dataset: the
current window is 1996-1997, years after the training period, and grocery price
levels trend.

## 4. Prediction drift

| metric | reference | current |
| --- | --- | --- |
| mean predicted units | {pred_check['reference_mean']:.3f} | {pred_check['current_mean']:.3f} |
| p95 predicted units | {pred_check['reference_p95']:.3f} | {pred_check['current_p95']:.3f} |
| share of zero predictions | {100*pred_check['share_zero_reference']:.2f}% | {100*pred_check['share_zero_current']:.2f}% |
| PSI | {pred_check['psi']:.4f} ({pred_check['band']}) | |
| KS | {pred_check['ks']:.4f} | |

## 5. Realised accuracy once outcomes arrive

| period | rows | MAE | RMSE | WAPE | bias |
| --- | --- | --- | --- | --- | --- |
{perf_rows}

## 6. What a production deployment would add (not built here)

* scheduled re-scoring and metric persistence (a table, not a JSON file);
* alerting thresholds agreed with the business, calibrated on historical
  variation rather than copied from a blog post;
* automatic fallback: if price-response validation fails for a series, the
  engine should degrade to `KEEP_CURRENT_PRICE` for that series rather than
  serving a suspect recommendation;
* champion/challenger model comparison on live traffic;
* retraining trigger tied to realised WAPE, not to drift alone.

These are named rather than faked: this repository implements the checks it can
verify offline, and states plainly what a real deployment would still need.
"""
    out = cfg.path("reports_dir") / "MONITORING_DESIGN.md"
    out.write_text(report, encoding="utf-8")
    print(f"wrote {out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
